### ISSUE TITLE
logistic regression error: Null pointer exception occurs when global epoch larger than 1

### ISSUE THREAD

**Issue by robbine** [TalkingData/Fregata#14]
here is the stack trace:
java.lang.NullPointerException
        at fregata.param.LocalParameterServer$$anonfun$adjust$1.apply$mcVID$sp(Parameter.scala:35)
        at fregata.util.VectorUtil$.forV(VectorUtil.scala:44)
        at fregata.param.LocalParameterServer.adjust(Parameter.scala:34)
        at fregata.optimize.sgd.StochasticGradientDescent$$anonfun$run$1.apply(StochasticGradientDescent.scala:25)
        at fregata.optimize.sgd.StochasticGradientDescent$$anonfun$run$1.apply(StochasticGradientDescent.scala:20)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
        at fregata.optimize.sgd.StochasticGradientDescent.run(StochasticGradientDescent.scala:20)
        at fregata.model.classification.LogisticRegression.run(LogisticRegression.scala:83)
        at fregata.model.classification.LogisticRegression.run(LogisticRegression.scala:74)
        at fregata.model.ModelTrainer$$anonfun$run$1.apply$mcVI$sp(ModelTrainer.scala:21)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at fregata.model.ModelTrainer$class.run(ModelTrainer.scala:19)
        at fregata.model.classification.LogisticRegression.run(LogisticRegression.scala:74)
        at fregata.spark.model.SparkTrainer$$anonfun$1.apply(SparkTrainer.scala:26)
        at fregata.spark.model.SparkTrainer$$anonfun$1.apply(SparkTrainer.scala:24)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
        at org.apache.spark.scheduler.Task.run(Task.scala:85)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

**Comment by robbine** [comment]
sorry, not an issue

**Comment by luowenjuan** [comment]
How did u solve this problem?
