### ISSUE TITLE
IndexOutOfBoundsException: 2 not in [-2,2)

### ISSUE THREAD

**Issue by kevinew** [TalkingData/Fregata#20]
I run the softmax with little data, but error
1 2:1.0 3:1.0
2 1:1.0 2:1.0 3:1.0
3 1:1.0 2:1.0 3:1.0

Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 7, executor id: 49, host: hadoop-afd-tretw.bj): java.lang.IndexOutOfBoundsException: 2 not in [-2,2)
	at breeze.linalg.DenseVector$mcD$sp.apply$mcD$sp(DenseVector.scala:71)
	at fregata.util.VectorUtil$$anonfun$wxpb$2.apply$mcVID$sp(VectorUtil.scala:29)
	at fregata.util.VectorUtil$.forV(VectorUtil.scala:44)

**Comment by takun2s** [comment]
The label should start from 0 .
0 2:1.0 3:1.0
1 1:1.0 2:1.0 3:1.0
2 1:1.0 2:1.0 3:1.0

**Comment by kevinew** [comment]
Setted the label start from o.  the same error jump out:
